CREATE TABLE if not exists guest (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   document VARCHAR(255),
   phone VARCHAR(255),
   CONSTRAINT pk_guest PRIMARY KEY (id)
);

ALTER TABLE guest ADD CONSTRAINT uc_guest_document UNIQUE (document);

ALTER TABLE guest ADD CONSTRAINT uc_guest_phone UNIQUE (phone);

CREATE TABLE reservation (
  id BIGINT NOT NULL,
   start_date date,
   end_date date,
   check_in TIMESTAMP WITHOUT TIME ZONE,
   check_out TIMESTAMP WITHOUT TIME ZONE,
   vehicle BOOLEAN NOT NULL,
   price INTEGER,
   guest_id BIGINT,
   CONSTRAINT pk_reservation PRIMARY KEY (id)
);

ALTER TABLE reservation ADD CONSTRAINT FK_RESERVATION_ON_GUEST FOREIGN KEY (guest_id) REFERENCES guest (id);